# this output block is exposing the ID of the AWS security group named videoipath
# you can view it after applying the configuration to see the actual value generated by AWS for the videoipath security group's ID.
output "security_group_id" {
  value = aws_security_group.instance-sg.id

}

output "mgmt-ec2" {
  value = aws_instance.mgmt-ec2.tags_all
}

output "node1-ec2" {
  value = aws_instance.node1-ec2.tags_all
}

output "node2-ec2" {
  value = aws_instance.node2-ec2.tags_all
}

output "node3-ec2" {
  value = aws_instance.node3-ec2.tags_all
}

output "aws_subnet" {
  value = "${var.environment}-${var.workflow}-az1-private-subnet-01"
}